-- Crear tabla para registrar operaciones
CREATE TABLE operaciones_calculadora (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero1 NUMBER(10,2),
    numero2 NUMBER(10,2),
    operacion VARCHAR2(20),
    resultado NUMBER(10,2),
    fecha TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Datos de prueba opcionales
INSERT INTO operaciones_calculadora (numero1, numero2, operacion, resultado)
VALUES (5, 3, 'SUMA', 8);

INSERT INTO operaciones_calculadora (numero1, numero2, operacion, resultado)
VALUES (10, 2, 'DIVISION', 5);

COMMIT; 